name: CI/CD

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11-dev"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v01

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U pip
          pip install -e .

      - name: Run examples in Python-${{ matrix.python-version }}
        run: |
          python3 examples/example01.py
          python3 examples/example02.py

      - uses: actions/upload-artifact@v3
        with:
          name: py-${{ matrix.python-version }}
          path: examples/
